//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMTest.Date
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
    {
        public int Id { get; set; }
        public string Descriotion { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public Nullable<int> DateExpiration { get; set; }
        public Nullable<int> Type { get; set; }
        public string MarksProduct { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Units { get; set; }
        public string Name { get; set; }
    
        public virtual TypeProduct TypeProduct { get; set; }
        public virtual Unit Unit { get; set; }

    }
}
